[package]
name = "fastmatcher"
version = "0.1.1"
edition = "2021"

[lib]
name = "fastmatcher"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
aho-corasick = "1.1"
rayon = "1.10"

[features]
default = []